# Generated by Django 3.2.4 on 2021-06-22 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answerId', models.AutoField(primary_key=True, serialize=False)),
                ('answerText', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('examId', models.AutoField(primary_key=True, serialize=False)),
                ('examNumber', models.IntegerField()),
                ('examStartDate', models.DateField()),
                ('examEndDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StudyGuide',
            fields=[
                ('studyGuideId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('typeOfStudyGuide', models.TextField()),
                ('file', models.BinaryField()),
                ('dateOfAssignment', models.DateField()),
                ('examId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RELA212EfficientizedApp.exam')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('questionGroupId', models.AutoField(primary_key=True, serialize=False)),
                ('scriptureBookName', models.TextField()),
                ('scriptureChapterNumber', models.IntegerField()),
                ('countOfQuestions', models.IntegerField()),
                ('studyGuideId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RELA212EfficientizedApp.studyguide')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionId', models.AutoField(primary_key=True, serialize=False)),
                ('questionText', models.TextField()),
                ('questionGroupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RELA212EfficientizedApp.questiongroup')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerLocation',
            fields=[
                ('answerLocationId', models.AutoField(primary_key=True, serialize=False)),
                ('answerLocationType', models.TextField()),
                ('scriptureBookName', models.TextField()),
                ('scriptureChapterNumber', models.IntegerField()),
                ('scriptureVerseNumber', models.IntegerField()),
                ('handoutCharacterStart', models.IntegerField()),
                ('handoutCharacterEnd', models.IntegerField()),
                ('answerId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RELA212EfficientizedApp.answer')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerHint',
            fields=[
                ('answerHintId', models.AutoField(primary_key=True, serialize=False)),
                ('answerHintType', models.TextField()),
                ('scriptureBookName', models.TextField()),
                ('scriptureChapterNumber', models.IntegerField()),
                ('scriptureVerseNumber', models.IntegerField()),
                ('handoutCharacterStart', models.IntegerField()),
                ('handoutCharacterEnd', models.IntegerField()),
                ('questionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RELA212EfficientizedApp.question')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='questionId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RELA212EfficientizedApp.question'),
        ),
    ]
