# Generated by Django 3.1.3 on 2021-06-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RELA212EfficientizedApp', '0002_auto_20210622_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyguide',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
