# Generated by Django 3.2.4 on 2021-06-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RELA212EfficientizedApp', '0003_auto_20210625_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerhint',
            name='hintText',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='isNote',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
